/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RandomName;
import java.sql.*;

/**
 *
 * @author rawa4r2d
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        HotelNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        usernameTextfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        passwordTextfield = new javax.swing.JPasswordField();
        WarningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIDEPANEL");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLabel.setFont(new java.awt.Font("Teko SemiBold", 0, 24)); // NOI18N
        UsernameLabel.setText("Username");
        jPanel1.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 101, 50));

        HotelNameLabel.setFont(new java.awt.Font("Teko SemiBold", 0, 48)); // NOI18N
        HotelNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        HotelNameLabel.setText("Hotel Name");
        HotelNameLabel.setAlignmentX(50.0F);
        HotelNameLabel.setAlignmentY(50.0F);
        HotelNameLabel.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(HotelNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 200, 52));

        PasswordLabel.setFont(new java.awt.Font("Teko SemiBold", 0, 24)); // NOI18N
        PasswordLabel.setText("Password");
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 101, -1));

        usernameTextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(usernameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 190, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Teko SemiBold", 0, 14)); // NOI18N
        jButton2.setText("Login");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 110, 40));
        jPanel1.add(passwordTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 190, 30));

        WarningLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WarningLabel.setForeground(new java.awt.Color(255, 0, 51));
        WarningLabel.setText("WRONG INFORMATION");
        WarningLabel.setFocusable(false);
        WarningLabel.setVisible(false);
        jPanel1.add(WarningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String UserName = usernameTextfield.getText();
        String Password = passwordTextfield.getText();
        boolean loginSuccessful = SQL.checkLogin(UserName, Password);

        if (loginSuccessful) {
            Home lhome = new Home();
            lhome.setVisible(true);
            
        } else {
            WarningLabel.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_jButton2MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HotelNameLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel UsernameLabel;
    public javax.swing.JLabel WarningLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordTextfield;
    private javax.swing.JTextField usernameTextfield;
    // End of variables declaration//GEN-END:variables
}
